import React, { Component } from 'react';
import './Containers.css';
import Identity from '../Identity';
import LoadingIndicator from '../../LoadingIndicator';
import Button from '../../Button';

class Containers extends Component {
  constructor(props) {
    super(props);
    this.state = {};
  }

  componentDidMount(){
    browser.storage.sync.get().then((data) => {
      this.setState(data)
    });
  }

  updatePref(){
    console.log(document.getElementById("regexTextBox").value);
    browser.storage.sync.set({regex: document.getElementById("regexTextBox").value})
  }

  render(){
    if(this.state.identities == undefined){
      return(
        <LoadingIndicator/>
      )
    }
    else{
      return(this.renderList())
    }
  }
  
  // renderTextBox(){
  //   console.log(this.state.regex);
  //   return(
      
  //   );
  // }

  renderList(){
    console.log(this.state.identities);
    var items = this.state.identities.map((identity) => {
        return (<Identity key={identity.name} name={identity.name} icon={identity.icon} color={identity.colorCode} />)
      });
    return(
      <div>
        <div className="preference">
          <h2>Preferences</h2>
          <label for="regexTextBox">Filter autogenerated containers using regex</label>
        <input className="pref-text" type="text" defaultValue={this.state.regex} id="regexTextBox"/>
        <Button style={{width: "90%", marginTop: "10px", textAlign: "center" }} onClick={this.updatePref}>Update</Button>
      </div>
      <hr/>
      <h2>Synced containers</h2>
      <table>
        <tbody>
          {items}
        </tbody>
      </table>
      
    </div>);
  }
}

export default Containers;